set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOLCHAIN_PREFIX arm-none-eabi)

set(CMAKE_C_COMPILER   ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}-gcc)

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}-objcopy CACHE INTERNAL "")
set(CMAKE_SIZE    ${TOOLCHAIN_PREFIX}-size CACHE INTERNAL "")
set(CMAKE_AR      ${TOOLCHAIN_PREFIX}-ar CACHE INTERNAL "")
set(CMAKE_RANLIB  ${TOOLCHAIN_PREFIX}-ranlib CACHE INTERNAL "")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
